### ISSUE TITLE
Testing getting cannot load

### ISSUE THREAD

**Issue by downright770** [sensu-plugins/sensu-plugins-nginx#13]
Hey trying to run a test on this so not sure if I'm doing something wrong.

 ./metrics-nginx.rb
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sensu-plugin/metric/cli (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./metrics-nginx.rb:29:in `<main>'

**Comment by eheydrick** [comment]
Hi @downright770 are you still experiencing this issue? How are you installing the plugin? It looks like the ruby that is running the check doesn't have the `sensu-plugin` gem installed. It's best to install plugins into the embedded ruby that ships with sensu as that will give you a modern version of ruby.

**Comment by majormoses** [comment]
closing due to lack of response, if you are still experiencing this issue reply back and I will be happy to try to help
