### ISSUE TITLE
latest release not found on rubygems

### ISSUE THREAD

**Issue by runningman84** [sensu-plugins/sensu-plugins-nginx#4]
please release the latest version to rubygems:
```
       ---- Begin output of /opt/sensu/embedded/bin/gem install sensu-plugins-nginx -q --no-rdoc --no-ri -v "0.0.3" ----
       STDOUT: 
       STDERR: ERROR:  Could not find a valid gem 'sensu-plugins-nginx' (= 0.0.4) in any repository
       ERROR:  Possible alternatives: sensu-plugins-nginx
```

**Comment by gabrieltholsgard** [comment]
@runningman84 I've noticed that the latest version is on rubygems, but under a different name.
sensu-plugins-nginx is only for version 0.0.1
sensu-plugins-sensu-plugins-ngnix have versions 0.0.4 and 0.0.3
You can check this yourself by running
gem list -ra sensu-plugins

It would be nice if they could update it to the more expected way for all versions, i.e sensu-plugins-nginx

**Comment by mattyjones** [comment]
@gabrieltholsgard @runningman84 

Done.  Sorry for the confusion

**Comment by gabrieltholsgard** [comment]
Thanks, just one more thing though

Could you update such that it is
sensu-plugins-nginx

currently it is
sensu-plugins-ngnix

**Comment by mattyjones** [comment]
@gabrieltholsgard should be building now.  :doh
